map ctrl+shift+h neighboring_window left
map ctrl+shift+l neighboring_window right
map ctrl+shift+j neighboring_window down
map ctrl+shift+k neighboring_window up

map ctrl+shift+left move_window left
map ctrl+shift+right move_window right
map ctrl+shift+down move_window down
map ctrl+shift+up move_window up

map ctrl+shift+Space next_layout

map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+Enter new_window_with_cwd

map ctrl+shift+f2 detach_window new-tab
map ctrl+shift+f3 detach_window

map ctrl+shift+[ show_scrollback

map ctrl+shift+x copy_ansi_to_clipboard

map ctrl+shift+g show_last_command_output
