map alt+h neighboring_window left
map alt+j neighboring_window down
map alt+k neighboring_window up
map alt+l neighboring_window right

map alt+shift+h move_window left
map alt+shift+j move_window down
map alt+shift+k move_window up
map alt+shift+l move_window right

map alt+Space next_layout

map alt+t new_tab_with_cwd
map alt+Enter new_window_with_cwd
map alt+x close_window

map alt+n detach_window new-tab
map alt+d detach_window
map alt+r load_config_file

map alt+[ show_scrollback

map alt+a copy_ansi_to_clipboard

map alt+g show_last_command_output

map alt+, previous_tab
map alt+. next_tab
