include mocha.conf
include binds.conf

window_padding_width 10

background_opacity 0.8

font_family Maple Mono
bold_font auto
italic_font auto
bold_italic_font auto
font_size 9.0

cursor none
mouse_hide_wait 1.0

shell /bin/zsh
editor /usr/bin/nvim

allow_remote_control yes

tab_title_template "{tab.active_wd}"
