#!/bin/sh

symbol() {
    [ $(cat /sys/class/net/w*/operstate) = down ] && echo "wifi-disconnected" && exit
    echo "wifi-connected"
}

name() {
    nmcli | grep "^wlan0" | sed 's/wlan0:\ \(unavailable\|disconnected\)//' | sed 's/\ connected\ to\ //' | cut -d ':' -f2
}

[ "$1" = "icon" ] && symbol && exit
[ "$1" = "name" ] && name && exit
