#!/bin/sh

workspaces() {


# active: at least 1 window open in workspace 
# visible: the current window
display_string=$(cat <<EOF
(box
    :class "works"
    :orientation "v"
    :halign "center"
    :valign "start"
    :space-evenly "false"
    :spacing "-5" 
EOF
)

src=$(i3-msg -t get_workspaces)
# get active windows
active_workspaces=$(echo $src | jq -c '.[] | .name')

# should have only 1 element in array
focused_workspaces=$(echo $src | jq -c '.[] | select(.focused == true) | .name')

for workspace in $active_workspaces
do

    if [ $focused_workspaces == $workspace ]
    then
        display_string+=$(cat <<EOF
            (button 
                :class "011"
                :onclick 'i3-msg workspace $workspace'
                $workspace
            ) 
EOF
    )
    else
        display_string+=$(cat <<EOF
            (button 
                :class "01"
                :onclick 'i3-msg workspace $workspace'
                $workspace
            ) 
EOF
    )
    fi
done

display_string+=")"
echo $display_string
}

workspaces 
i3-msg -t subscribe -m '[ "window", "workspace" ]' | while read line ; do workspaces; done

# bspc subscribe desktop node_transfer | while read -r _ ; do
# workspaces
# done
#
#
# (box 
#     :class "works" 
#     :orientation "v" 
#     :halign "center" 
#     :valign "start" 
#     :space-evenly "false" 
#     :spacing "-5" 
#     (button 
#         :class "011" 
#         :onclick "i3-msg workspace 1"
#         "1" 
#     )
#     (button 
#         :class "01" 
#         :onclick 'i3-msg workspace "2"'
#         "2" 
#     )
# ))
