source = ~/.config/hypr/themes/mocha.conf
$font = Maple Mono

general {
  hide_cursor = true
}

auth {
  fingerprint {
    enabled = true
    ready_message = Scan fingerprint to unlock
    present_message = Scanning...
    retry_delay = 250
  }
}

background {
  monitor =
  path = /home/samuzora/.config/hypr/wallpapers/bg-dark.png
  blur_passes = 1
}

input-field {
  monitor =

  halign = center
  valign = bottom
  position = 0, 50
  size = 1000, 90
  rounding = 10
  dots_center = false
  dots_size = 0.2

  outline_thickness = 3
  inner_color = rgba($baseAlphabb)
  outer_color = $sky $mauve 60deg
  check_color = $yellow $mauve 60deg
  fail_color =  $red $mauve 60deg

  font_family = $font
  font_color = $text
  fade_on_empty = true
  placeholder_text = Enter password...
  fail_text = $PAMFAIL
  dots_spacing = 0.3
}

animations {
  enabled = true
}

# --- components ---
# TIME
label {
    monitor =
    text = $TIME
    font_size = 90
    font_family = $font

    position = -30, 0
    halign = right
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    font_size = 25
    font_family = $font

    position = -30, -150
    halign = right
    valign = top
}

# fingerprint
label {
  monitor =
  halign = center
  valign = bottom
  position = 0, 200
  text = $FPRINTPROMPT
  font_size = 20
  font_family = $font
  color = $text
}
