#!/bin/sh

calendar(){
LOCK_FILE="$HOME/.cache/eww-calendar.lock"
EWW_BIN="/usr/bin/eww"

run() {
    ${EWW_BIN} -c $HOME/.config/eww open calendar
}

# Run eww daemon if not running
if [[ ! `pidof eww` ]]; then
    ${EWW_BIN} daemon
    sleep 1
fi

# Open widgets
if [[ ! -f "$LOCK_FILE" ]]; then
    touch "$LOCK_FILE"
    run
else
    ${EWW_BIN} -c $HOME/.config/eww close calendar
    rm "$LOCK_FILE"
fi
}

if [ "$1" = "launcher" ]; then
$HOME/.local/bin/launcher
elif [ "$1" = "wifi" ]; then
$HOME/.config/i3/rofi/bin/network_menu
elif [ "$1" = "audio" ]; then
pavucontrol
elif [ "$1" = "calendar" ]; then
calendar
fi
