#!/bin/sh

symbol() {
    [ $(cat /sys/class/net/w*/operstate) = down ] && echo "wifi-disconnected" && exit
    echo "wifi-connected"
}

name() {
    nmcli device show wlan0 | sed -n "s/GENERAL.CONNECTION:\s*\(.*\)/\1/p"
}

[ "$1" = "class" ] && symbol && exit
[ "$1" = "name" ] && name && exit
