#!/bin/sh

workspaces() {


# active: at least 1 window open in workspace 
# visible: the current window
display_string=$(cat <<EOF
(box
:valign "center"
:class "workspaces"
:spacing 30
EOF
)

src=$(i3-msg -t get_workspaces)

# get active windows
active_workspaces=$(sort<<<$(echo $src | jq '.[] | .name'))

# TODO: handle multi-monitor setup
# should have only 1 element in array
focused_workspaces=$(echo $src | jq '.[] | select(.focused == true) | .name')


for i in {1..9}
do
    if [[ $focused_workspaces =~ $i ]]; then
        display_string+=$(cat <<EOF
        (button 
        :class "workspace focused"
        :onclick 'i3-msg workspace $i'
        ""
        ) 
EOF
        )
    elif [[ $active_workspaces[*] =~ $i ]]; then
        display_string+=$(cat <<EOF
        (button 
        :class "workspace active"
        :onclick 'i3-msg workspace $i'
        ""
        ) 
EOF
        )
    else 
        display_string+=$(cat <<EOF
        (button
        :class "workspace"
        :onclick 'i3-msg workspace $i'
        ""
        )
EOF
        )
    fi
done


display_string+=")"
echo $display_string
}

workspaces 
i3-msg -t subscribe -m '[ "workspace" ]' | while read line ; do workspaces; done
